// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: srcjflexcup/lexer.flex

/* JFlex example: partial Java language lexer specification */
package esercitazione5;
import java_cup.runtime.*;
import java.util.List;
import java.util.ArrayList;

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\1\1\5"+
    "\1\6\1\0\1\7\1\0\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\11\23"+
    "\1\24\1\25\1\26\1\27\1\30\2\0\32\7\1\0"+
    "\1\31\1\0\1\32\1\7\1\0\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\2\7\1\44"+
    "\1\7\1\45\1\46\1\47\1\7\1\50\1\51\1\52"+
    "\1\53\1\54\1\55\3\7\1\56\1\57\1\60\7\0"+
    "\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\1\1\3\1\4\1\5\1\1"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\2\16\1\17\1\20\1\21\1\22\1\23\1\24\20\4"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\0"+
    "\1\34\3\0\1\16\1\0\1\35\1\36\1\37\4\4"+
    "\1\40\4\4\1\41\1\42\4\4\1\43\5\4\1\44"+
    "\4\4\1\0\1\2\1\45\1\46\1\47\1\50\1\51"+
    "\1\52\1\53\1\54\2\4\1\55\3\4\1\56\1\4"+
    "\1\57\1\4\1\60\1\4\1\61\5\4\1\62\3\4"+
    "\1\63\1\4\1\64\1\65\3\4\1\66\4\4\1\67"+
    "\1\70\1\71\1\72\2\4\1\73\1\74\5\4\1\75"+
    "\3\4\1\76\1\77\1\100\1\101\1\102\2\4\1\103";

  private static int [] zzUnpackAction() {
    int [] result = new int[154];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\142\0\142\0\223\0\304\0\142\0\365"+
    "\0\142\0\u0126\0\142\0\142\0\142\0\142\0\142\0\u0157"+
    "\0\142\0\142\0\u0188\0\u01b9\0\142\0\142\0\u01ea\0\142"+
    "\0\u021b\0\142\0\u024c\0\u027d\0\u02ae\0\u02df\0\u0310\0\u0341"+
    "\0\u0372\0\u03a3\0\u03d4\0\u0405\0\u0436\0\u0467\0\u0498\0\u04c9"+
    "\0\u04fa\0\u052b\0\142\0\u055c\0\142\0\u058d\0\142\0\u05be"+
    "\0\142\0\u05ef\0\142\0\u0620\0\u0651\0\u0682\0\u06b3\0\u06e4"+
    "\0\142\0\142\0\142\0\u0715\0\u0746\0\u0777\0\u07a8\0\365"+
    "\0\u07d9\0\u080a\0\u083b\0\u086c\0\365\0\365\0\u089d\0\u08ce"+
    "\0\u08ff\0\u0930\0\365\0\u0961\0\u0992\0\u09c3\0\u09f4\0\u0a25"+
    "\0\365\0\u0a56\0\u0a87\0\u0ab8\0\u0ae9\0\u0b1a\0\u0b4b\0\142"+
    "\0\142\0\142\0\142\0\u0b7c\0\u0682\0\142\0\365\0\u0bad"+
    "\0\u0bde\0\365\0\u0c0f\0\u0c40\0\u0c71\0\365\0\u0ca2\0\365"+
    "\0\u0cd3\0\365\0\u0d04\0\365\0\u0d35\0\u0d66\0\u0d97\0\u0dc8"+
    "\0\u0df9\0\365\0\u0e2a\0\u0e5b\0\u0e8c\0\142\0\u0ebd\0\365"+
    "\0\365\0\u0eee\0\u0f1f\0\u0f50\0\365\0\u0f81\0\u0fb2\0\u0fe3"+
    "\0\u1014\0\365\0\365\0\365\0\365\0\u1045\0\u1076\0\365"+
    "\0\365\0\u10a7\0\u10d8\0\u1109\0\u113a\0\u116b\0\365\0\u119c"+
    "\0\u11cd\0\u11fe\0\365\0\142\0\365\0\365\0\365\0\u122f"+
    "\0\u1260\0\365";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[154];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\3\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\3\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\10\1\42\1\43\1\44\1\45\1\10\1\46"+
    "\1\47\1\50\1\10\1\51\1\52\1\53\1\54\1\55"+
    "\2\56\1\3\1\56\1\3\1\56\1\57\22\56\1\60"+
    "\27\56\63\0\1\4\105\0\1\61\40\0\1\10\12\0"+
    "\2\10\7\0\23\10\3\0\6\62\1\0\2\62\1\63"+
    "\17\62\1\64\2\62\1\0\3\62\1\0\4\62\1\0"+
    "\2\62\1\0\1\62\1\0\6\62\17\0\1\65\41\0"+
    "\2\66\3\0\56\66\3\0\15\66\2\67\35\66\17\0"+
    "\1\70\6\0\1\71\1\72\1\61\57\0\1\73\40\0"+
    "\1\10\12\0\2\10\7\0\12\10\1\74\10\10\12\0"+
    "\1\10\12\0\2\10\7\0\13\10\1\75\7\10\12\0"+
    "\1\10\12\0\2\10\7\0\7\10\1\76\13\10\12\0"+
    "\1\10\12\0\2\10\7\0\4\10\1\77\6\10\1\100"+
    "\7\10\12\0\1\10\12\0\2\10\7\0\11\10\1\101"+
    "\11\10\12\0\1\10\12\0\2\10\7\0\1\102\10\10"+
    "\1\103\1\10\1\104\7\10\12\0\1\10\12\0\2\10"+
    "\7\0\13\10\1\105\7\10\12\0\1\10\12\0\2\10"+
    "\7\0\5\10\1\106\4\10\1\107\10\10\12\0\1\10"+
    "\12\0\2\10\7\0\4\10\1\110\6\10\1\111\7\10"+
    "\12\0\1\10\12\0\2\10\7\0\13\10\1\112\7\10"+
    "\12\0\1\10\12\0\2\10\7\0\15\10\1\113\1\10"+
    "\1\114\1\115\2\10\12\0\1\10\12\0\2\10\7\0"+
    "\4\10\1\116\16\10\12\0\1\10\12\0\2\10\7\0"+
    "\17\10\1\117\3\10\12\0\1\10\12\0\2\10\7\0"+
    "\7\10\1\120\3\10\1\121\1\10\1\122\5\10\12\0"+
    "\1\10\12\0\2\10\7\0\1\123\12\10\1\124\7\10"+
    "\12\0\1\10\12\0\2\10\7\0\7\10\1\125\13\10"+
    "\17\0\1\126\42\0\1\127\1\0\2\56\1\0\1\56"+
    "\1\0\1\56\1\0\22\56\1\0\27\56\6\0\1\130"+
    "\36\0\1\131\2\0\1\132\1\0\1\133\17\0\1\63"+
    "\55\0\1\62\2\0\1\62\17\0\1\62\2\0\1\62"+
    "\3\0\1\62\4\0\1\62\2\0\1\62\1\0\1\62"+
    "\36\0\1\134\52\0\2\135\57\0\2\67\54\0\1\136"+
    "\50\0\1\10\12\0\2\10\7\0\3\10\1\137\17\10"+
    "\12\0\1\10\12\0\2\10\7\0\13\10\1\140\7\10"+
    "\12\0\1\10\12\0\2\10\7\0\1\141\22\10\12\0"+
    "\1\10\12\0\2\10\7\0\5\10\1\142\15\10\12\0"+
    "\1\10\12\0\2\10\7\0\16\10\1\143\4\10\12\0"+
    "\1\10\12\0\2\10\7\0\11\10\1\144\11\10\12\0"+
    "\1\10\12\0\2\10\7\0\13\10\1\145\7\10\12\0"+
    "\1\10\12\0\2\10\7\0\15\10\1\146\5\10\12\0"+
    "\1\10\12\0\2\10\7\0\17\10\1\147\3\10\12\0"+
    "\1\10\12\0\2\10\7\0\17\10\1\150\3\10\12\0"+
    "\1\10\12\0\2\10\7\0\13\10\1\151\7\10\12\0"+
    "\1\10\12\0\2\10\7\0\17\10\1\152\3\10\12\0"+
    "\1\10\12\0\2\10\7\0\7\10\1\153\13\10\12\0"+
    "\1\10\12\0\2\10\7\0\17\10\1\154\3\10\12\0"+
    "\1\10\12\0\2\10\7\0\17\10\1\155\3\10\12\0"+
    "\1\10\12\0\2\10\7\0\1\156\14\10\1\157\5\10"+
    "\12\0\1\10\12\0\2\10\7\0\4\10\1\160\16\10"+
    "\12\0\1\10\12\0\2\10\7\0\20\10\1\161\2\10"+
    "\12\0\1\10\12\0\2\10\7\0\15\10\1\162\5\10"+
    "\12\0\1\10\12\0\2\10\7\0\10\10\1\163\12\10"+
    "\12\0\1\10\12\0\2\10\7\0\4\10\1\164\3\10"+
    "\1\165\12\10\3\0\57\126\1\4\1\126\2\127\1\4"+
    "\1\127\1\5\54\127\5\0\1\166\62\0\1\10\12\0"+
    "\2\10\7\0\11\10\1\167\11\10\12\0\1\10\12\0"+
    "\2\10\7\0\15\10\1\170\5\10\12\0\1\10\12\0"+
    "\2\10\7\0\4\10\1\171\16\10\12\0\1\10\12\0"+
    "\2\10\7\0\16\10\1\172\4\10\12\0\1\10\12\0"+
    "\2\10\7\0\1\173\22\10\12\0\1\10\12\0\2\10"+
    "\7\0\4\10\1\174\16\10\12\0\1\10\12\0\2\10"+
    "\7\0\14\10\1\175\6\10\12\0\1\10\12\0\2\10"+
    "\7\0\4\10\1\176\16\10\12\0\1\10\12\0\2\10"+
    "\7\0\20\10\1\177\2\10\12\0\1\10\12\0\2\10"+
    "\7\0\15\10\1\200\5\10\12\0\1\10\12\0\2\10"+
    "\7\0\10\10\1\201\12\10\12\0\1\10\12\0\2\10"+
    "\7\0\12\10\1\202\10\10\12\0\1\10\12\0\2\10"+
    "\7\0\4\10\1\203\16\10\12\0\1\10\12\0\2\10"+
    "\7\0\3\10\1\204\17\10\12\0\1\10\12\0\2\10"+
    "\7\0\12\10\1\205\10\10\12\0\1\10\12\0\2\10"+
    "\7\0\11\10\1\206\11\10\12\0\1\10\12\0\2\10"+
    "\7\0\4\10\1\207\16\10\12\0\1\10\12\0\2\10"+
    "\7\0\4\10\1\210\16\10\12\0\1\10\12\0\2\10"+
    "\7\0\17\10\1\211\3\10\12\0\1\10\12\0\2\10"+
    "\7\0\6\10\1\212\14\10\12\0\1\10\12\0\2\10"+
    "\7\0\15\10\1\213\5\10\12\0\1\10\12\0\2\10"+
    "\7\0\15\10\1\214\5\10\12\0\1\10\12\0\2\10"+
    "\7\0\17\10\1\215\3\10\12\0\1\10\12\0\2\10"+
    "\7\0\12\10\1\216\10\10\12\0\1\10\12\0\2\10"+
    "\7\0\4\10\1\217\16\10\12\0\1\10\12\0\2\10"+
    "\7\0\1\220\22\10\12\0\1\10\12\0\2\10\7\0"+
    "\4\10\1\221\16\10\12\0\1\10\12\0\2\10\7\0"+
    "\22\10\1\222\12\0\1\10\12\0\2\10\7\0\12\10"+
    "\1\223\10\10\12\0\1\10\12\0\2\10\1\224\6\0"+
    "\23\10\12\0\1\10\12\0\2\10\7\0\6\10\1\225"+
    "\14\10\12\0\1\10\12\0\2\10\7\0\12\10\1\226"+
    "\10\10\12\0\1\10\12\0\2\10\7\0\15\10\1\227"+
    "\5\10\12\0\1\10\12\0\2\10\7\0\10\10\1\230"+
    "\12\10\12\0\1\10\12\0\2\10\7\0\16\10\1\231"+
    "\4\10\12\0\1\10\12\0\2\10\7\0\4\10\1\232"+
    "\16\10\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4753];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\2\1\1\11\1\1\1\11\1\1\5\11"+
    "\1\1\2\11\2\1\2\11\1\1\1\11\1\1\1\11"+
    "\20\1\1\11\1\1\1\11\1\1\1\11\1\1\1\11"+
    "\1\0\1\11\3\0\1\1\1\0\3\11\32\1\1\0"+
    "\1\1\4\11\2\1\1\11\27\1\1\11\35\1\1\11"+
    "\6\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[154];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
  StringBuffer string = new StringBuffer();
  public List<String> identifiersTable = new ArrayList<>();


  private Symbol symbol(int type) {
    return new Symbol(type, yyline, yycolumn);
  }
  private Symbol symbol(int type, Object value) {
    return new Symbol(type, yyline, yycolumn, value);
  }

  private Symbol installID(String identifier) {
    if(!identifiersTable.contains(identifier))
        identifiersTable.add(identifier);
    return symbol(Sym.ID, ((Integer)identifiersTable.indexOf(identifier)));
  }





  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case STRING: {
              throw new IllegalArgumentException("unclosed string literal");
            }  // fall though
            case 155: break;
            default:
          { return new java_cup.runtime.Symbol(Sym.EOF); }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new Error("Illegal character <"+
                                                    yytext()+">");
            }
            // fall through
          case 68: break;
          case 2:
            { /* ignore */
            }
            // fall through
          case 69: break;
          case 3:
            { string.setLength(0); yybegin(STRING);
            }
            // fall through
          case 70: break;
          case 4:
            { return installID(yytext());
            }
            // fall through
          case 71: break;
          case 5:
            { return symbol(Sym.STR_CONCAT, "STR_CONCAT");
            }
            // fall through
          case 72: break;
          case 6:
            { return symbol(Sym.LPAR, "LPAR");
            }
            // fall through
          case 73: break;
          case 7:
            { return symbol(Sym.RPAR, "RPAR");
            }
            // fall through
          case 74: break;
          case 8:
            { return symbol(Sym.TIMES, "TIMES");
            }
            // fall through
          case 75: break;
          case 9:
            { return symbol(Sym.PLUS, "PLUS");
            }
            // fall through
          case 76: break;
          case 10:
            { return symbol(Sym.COMMA, "COMMA");
            }
            // fall through
          case 77: break;
          case 11:
            { return symbol(Sym.MINUS, "MINUS");
            }
            // fall through
          case 78: break;
          case 12:
            { return symbol(Sym.DOT, "DOT");
            }
            // fall through
          case 79: break;
          case 13:
            { return symbol(Sym.DIV, "DIV");
            }
            // fall through
          case 80: break;
          case 14:
            { return symbol(Sym.INTEGER_CONST, Integer.parseInt(yytext()));
            }
            // fall through
          case 81: break;
          case 15:
            { return symbol(Sym.COLON, "COLON");
            }
            // fall through
          case 82: break;
          case 16:
            { return symbol(Sym.SEMI, "SEMI");
            }
            // fall through
          case 83: break;
          case 17:
            { return symbol(Sym.LT, "LT");
            }
            // fall through
          case 84: break;
          case 18:
            { return symbol(Sym.EQ, "EQ");
            }
            // fall through
          case 85: break;
          case 19:
            { return symbol(Sym.GT, "GT");
            }
            // fall through
          case 86: break;
          case 20:
            { return symbol(Sym.POW, "POW");
            }
            // fall through
          case 87: break;
          case 21:
            { return symbol(Sym.LBRACK, "LBRACK");
            }
            // fall through
          case 88: break;
          case 22:
            { return symbol(Sym.PIPE, "PIPE");
            }
            // fall through
          case 89: break;
          case 23:
            { return symbol(Sym.RBRACK, "RBRACK");
            }
            // fall through
          case 90: break;
          case 24:
            { string.append( yytext() );
            }
            // fall through
          case 91: break;
          case 25:
            { yybegin(YYINITIAL);
                                     return symbol(Sym.STRING_CONST,
                                     string.toString());
            }
            // fall through
          case 92: break;
          case 26:
            { string.append('\\');
            }
            // fall through
          case 93: break;
          case 27:
            { return symbol(Sym.NE, "NE");
            }
            // fall through
          case 94: break;
          case 28:
            { if(yytext().length()==2) return symbol(Sym.CHAR_CONST, '\0');
                                   if(yytext().length()==3) return symbol(Sym.CHAR_CONST, yytext().charAt(1));
                                   return symbol(Sym.CHAR_CONST, yytext().charAt(2));
            }
            // fall through
          case 95: break;
          case 29:
            { return symbol(Sym.ASSIGN, "ASSIGN");
            }
            // fall through
          case 96: break;
          case 30:
            { return symbol(Sym.LE, "LE");
            }
            // fall through
          case 97: break;
          case 31:
            { return symbol(Sym.GE, "GE");
            }
            // fall through
          case 98: break;
          case 32:
            { return symbol(Sym.DO, "DO");
            }
            // fall through
          case 99: break;
          case 33:
            { return symbol(Sym.GO, "GO");
            }
            // fall through
          case 100: break;
          case 34:
            { return symbol(Sym.IF, "IF");
            }
            // fall through
          case 101: break;
          case 35:
            { return symbol(Sym.OR, "OR");
            }
            // fall through
          case 102: break;
          case 36:
            { return symbol(Sym.TO, "TO");
            }
            // fall through
          case 103: break;
          case 37:
            { string.append('\"');
            }
            // fall through
          case 104: break;
          case 38:
            { string.append('\n');
            }
            // fall through
          case 105: break;
          case 39:
            { string.append('\r');
            }
            // fall through
          case 106: break;
          case 40:
            { string.append('\t');
            }
            // fall through
          case 107: break;
          case 41:
            { return symbol(Sym.WRITE, "WRITE");
            }
            // fall through
          case 108: break;
          case 42:
            { return symbol(Sym.REAL_CONST, Float.parseFloat(yytext()));
            }
            // fall through
          case 109: break;
          case 43:
            { return symbol(Sym.READ, "READ");
            }
            // fall through
          case 110: break;
          case 44:
            { return symbol(Sym.AND, "AND");
            }
            // fall through
          case 111: break;
          case 45:
            { return symbol(Sym.DEF, "DEF");
            }
            // fall through
          case 112: break;
          case 46:
            { return symbol(Sym.FOR, "FOR");
            }
            // fall through
          case 113: break;
          case 47:
            { return symbol(Sym.LET, "LET");
            }
            // fall through
          case 114: break;
          case 48:
            { return symbol(Sym.NOT, "NOT");
            }
            // fall through
          case 115: break;
          case 49:
            { return symbol(Sym.OUT, "OUT");
            }
            // fall through
          case 116: break;
          case 50:
            { return symbol(Sym.VAR, "VAR");
            }
            // fall through
          case 117: break;
          case 51:
            { return symbol(Sym.WRITELN, "WRITELN");
            }
            // fall through
          case 118: break;
          case 52:
            { return symbol(Sym.CHAR, "CHAR");
            }
            // fall through
          case 119: break;
          case 53:
            { return symbol(Sym.ELSE, "ELSE");
            }
            // fall through
          case 120: break;
          case 54:
            { return symbol(Sym.LOOP, "LOOP");
            }
            // fall through
          case 121: break;
          case 55:
            { return symbol(Sym.THEN, "THEN");
            }
            // fall through
          case 122: break;
          case 56:
            { return symbol(Sym.TRUE, "TRUE");
            }
            // fall through
          case 123: break;
          case 57:
            { return symbol(Sym.VOID, "VOID");
            }
            // fall through
          case 124: break;
          case 58:
            { return symbol(Sym.WHEN, "WHEN");
            }
            // fall through
          case 125: break;
          case 59:
            { return symbol(Sym.FALSE, "FALSE");
            }
            // fall through
          case 126: break;
          case 60:
            { return symbol(Sym.REAL, "FLOAT");
            }
            // fall through
          case 127: break;
          case 61:
            { return symbol(Sym.WHILE, "WHILE");
            }
            // fall through
          case 128: break;
          case 62:
            { return symbol(Sym.RETURN, "RETURN");
            }
            // fall through
          case 129: break;
          case 63:
            { return symbol(Sym.MAIN, "MAIN");
            }
            // fall through
          case 130: break;
          case 64:
            { return symbol(Sym.STRING, "STRING");
            }
            // fall through
          case 131: break;
          case 65:
            { return symbol(Sym.BOOLEAN, "BOOLEAN");
            }
            // fall through
          case 132: break;
          case 66:
            { return symbol(Sym.INTEGER, "INTEGER");
            }
            // fall through
          case 133: break;
          case 67:
            { return symbol(Sym.OTHERWISE, "OTHERWISE");
            }
            // fall through
          case 134: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Converts an int token code into the name of the
   * token by reflection on the cup symbol class/interface Sym
   */
  private static String getTokenName(int token) {
    try {
      java.lang.reflect.Field [] classFields = Sym.class.getFields();
      for (int i = 0; i < classFields.length; i++) {
        if (classFields[i].getInt(null) == token) {
          return classFields[i].getName();
        }
      }
    } catch (Exception e) {
      e.printStackTrace(System.err);
    }

    return "UNKNOWN TOKEN";
  }

  /**
   * Same as next_token but also prints the token to standard out
   * for debugging.
   */
  public java_cup.runtime.Symbol debug_next_token() throws java.io.IOException {
    java_cup.runtime.Symbol s = next_token();
    System.out.println( "line:" + (yyline+1) + " col:" + (yycolumn+1) + " --"+ yytext() + "--" + getTokenName(s.sym) + "--");
    return s;
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String[] argv) {
    if (argv.length == 0) {
      System.out.println("Usage : java Lexer [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          // Side-effect: is encodingName valid?
          java.nio.charset.Charset.forName(encodingName);
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        Lexer scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new Lexer(reader);
          while ( !scanner.zzAtEOF ) scanner.debug_next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
