
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package esercitazione5;

/** CUP generated interface containing symbol constants. */
public interface Sym {
  /* terminals */
  public static final int CHAR_CONST = 53;
  public static final int OTHERWISE = 58;
  public static final int WHEN = 57;
  public static final int POW = 36;
  public static final int CHAR = 9;
  public static final int GE = 40;
  public static final int INTEGER_CONST = 50;
  public static final int INTEGER = 5;
  public static final int SEMI = 4;
  public static final int OUT = 21;
  public static final int FOR = 29;
  public static final int MINUS = 32;
  public static final int WRITE = 46;
  public static final int NOT = 48;
  public static final int AND = 35;
  public static final int LT = 41;
  public static final int RPAR = 16;
  public static final int OR = 38;
  public static final int COMMA = 10;
  public static final int DIV = 34;
  public static final int LOOP = 26;
  public static final int PLUS = 31;
  public static final int WRITELN = 47;
  public static final int ASSIGN = 11;
  public static final int MAIN = 2;
  public static final int IF = 22;
  public static final int DOT = 56;
  public static final int ID = 49;
  public static final int LE = 42;
  public static final int EOF = 0;
  public static final int BOOLEAN = 6;
  public static final int RETURN = 27;
  public static final int TRUE = 12;
  public static final int error = 1;
  public static final int PIPE = 20;
  public static final int VOID = 28;
  public static final int EQ = 43;
  public static final int LBRACK = 18;
  public static final int REAL = 7;
  public static final int TIMES = 33;
  public static final int COLON = 17;
  public static final int ELSE = 24;
  public static final int READ = 45;
  public static final int RBRACK = 19;
  public static final int TO = 30;
  public static final int WHILE = 25;
  public static final int LET = 54;
  public static final int STR_CONCAT = 37;
  public static final int REAL_CONST = 51;
  public static final int THEN = 23;
  public static final int NE = 44;
  public static final int LPAR = 15;
  public static final int STRING = 8;
  public static final int DEF = 14;
  public static final int FALSE = 13;
  public static final int STRING_CONST = 52;
  public static final int GT = 39;
  public static final int VAR = 3;
  public static final int DO = 59;
  public static final int GO = 55;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAIN",
  "VAR",
  "SEMI",
  "INTEGER",
  "BOOLEAN",
  "REAL",
  "STRING",
  "CHAR",
  "COMMA",
  "ASSIGN",
  "TRUE",
  "FALSE",
  "DEF",
  "LPAR",
  "RPAR",
  "COLON",
  "LBRACK",
  "RBRACK",
  "PIPE",
  "OUT",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "LOOP",
  "RETURN",
  "VOID",
  "FOR",
  "TO",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "AND",
  "POW",
  "STR_CONCAT",
  "OR",
  "GT",
  "GE",
  "LT",
  "LE",
  "EQ",
  "NE",
  "READ",
  "WRITE",
  "WRITELN",
  "NOT",
  "ID",
  "INTEGER_CONST",
  "REAL_CONST",
  "STRING_CONST",
  "CHAR_CONST",
  "LET",
  "GO",
  "DOT",
  "WHEN",
  "OTHERWISE",
  "DO"
  };
}

